ppo_hyperparameters:
  ppo_epochs: 6
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  actor_learning_rate: 2e-4
  critic_learning_rate: 1e-4

architecture:
  lstm_hidden_size: 256
  feature_dim: 256
