training:
  training_timesteps: 30001
  simulation_timesteps: 150 #30
  timestep: 0
  rollout_phases: 1
  batch_size: 512
  worlds_parallised: 512 # 960
  seed: -1 #73
  periodic_save_interval: 1000
